apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-scripts
  namespace: infra
data:
  changelog.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
            http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">

      <changeSet id="1" author="ally">
        <createTable tableName="tenants">
          <column name="id" type="UUID">
            <constraints primaryKey="true" />
          </column>
          <column name="name" type="varchar(255)" />
        </createTable>
      </changeSet>

    </databaseChangeLog>
