apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-config
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  FEATURE_AUTH_ENABLED: {{ .Values.env.FEATURE_AUTH_ENABLED | quote }}
