apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ include "common.fullname" . }}-config
          env:
            - name: PULSAR_BROKER_URL
              value: {{ .Values.env.PULSAR_BROKER_URL | quote }}
            - name: POSTGRES_URL
              value: {{ .Values.env.POSTGRES_URL | quote }}
            - name: REDIS_URL
              value: {{ .Values.env.REDIS_URL | quote }}
          ports:
            - containerPort: 4000
