apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-secrets
type: Opaque
stringData:
  DATABASE_URL: postgres://hradmin:hrpass@postgresql.infra.svc.cluster.local:5432/hr
  REDIS_URL: redis://redis.infra.svc.cluster.local:6379
