replicaCount: 1

image:
  repository: ghcr.io/amashr/hr-web
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: mobile.amashr.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
