name: Deploy to Kubernetes

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Configure kubectl
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Helm Upgrade Infra
        run: helm upgrade --install infra ./k8s/charts/infra -n infra

      - name: Helm Upgrade Microservices
        run: helm upgrade --install microservices ./k8s/charts/microservices -n microservices

      - name: Helm Upgrade Frontend
        run: helm upgrade --install frontend ./k8s/charts/frontend -n frontend
